---
branches:
  - main
plugins:
  - "@semantic-release/commit-analyzer"
  - preset: conventionalcommits
    releaseRules:
      - type: release
        release: major
      - type: ci
        release: minor
      - docs: 
        release: patch
  - "@semantic-release/release-notes-generator"
  - preset: conventionalcommits
    presetConfig:
      types:
        - type: release
          section: "release "
        - type: ci
          section: "ci "
        - type: feat
          section: "feat "
        - type: docs
          section: "docs "

  - - "@semantic-release/changelog"
    - changelogFile: docs/CHANGELOG.md 
  - - "@semantic-release/github"
    - assets: "pack/*.tgz"

  - - "@semantic-release/git"
    - message: |
        chore(release): ${nextRelease.version} [skip ci]

        ${nextRelease.notes}

