# Generated by Django 5.2.8 on 2025-12-27 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('griz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='age',
        ),
        migrations.AddField(
            model_name='dog',
            name='birthday',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
