# Generated by Django 5.2.8 on 2025-12-27 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('griz', '0002_remove_dog_age_dog_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='youtube_embed',
            field=models.URLField(blank=True, null=True),
        ),
    ]
