# Generated by Django 5.2.8 on 2026-01-11 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, db_index=True, null=True)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('youtube_embed', models.URLField(blank=True, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='entries', to='tech.tag')),
            ],
        ),
    ]
